// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_withcontext is generated so this documented storage example remains directly runnable.
package main

import (
	"context"
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
	"time"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// WithContext returns a derived storage handle bound to ctx for subsequent operations.

	// Example: bind a timeout to storage operations
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-with-context",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	data, _ := disk.WithContext(ctx).Get("docs/readme.txt")
	fmt.Println(string(data))
	// Output: hello
}
