// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command rclonestorage_new_rclone_storage is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/rclonestorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs an rclone-backed storage. All disks share a single config path.

	// Example: rclone storage
	fs, _ := rclonestorage.New(rclonestorage.Config{
		Remote: "local:",
		Prefix: "sandbox",
	})
	_ = fs

}
