// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_url_handle_unsupported_url_generation is generated so this documented storage example remains directly runnable.
package main

import (
	"errors"
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// URL returns a usable access URL when the driver supports it.

	// Example: handle unsupported url generation
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-url",
	})

	_, err := disk.URL("docs/readme.txt")
	fmt.Println(errors.Is(err, storage.ErrUnsupported))
	// Output: true
}
