// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"errors"
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// URL returns a usable access URL when the driver supports it.

	// Example: handle unsupported url generation
	disk, _ := storage.Build(localstorage.Config{
		Remote: "/tmp/storage-url",
	})

	_, err := disk.URL("docs/readme.txt")
	fmt.Println(errors.Is(err, storage.ErrUnsupported))
	// Output: true
}
