version: 2
updates:
  - { package-ecosystem: github-actions, directory: /, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /docs/bench, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /storagecore, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /storagetest, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /examples, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /integration, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/dropboxstorage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/ftpstorage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/gcsstorage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/localstorage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/memorystorage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/rclonestorage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/redisstorage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/s3storage, schedule: { interval: weekly } }
  - { package-ecosystem: gomod, directory: /driver/sftpstorage, schedule: { interval: weekly } }
