# for integration testing
# s3 - minio
# sftp - emberstack/sftp

services:
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: fsuser
      MINIO_ROOT_PASSWORD: fspass123
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  sftp:
    image: lscr.io/linuxserver/openssh-server:latest
    ports:
      - "2222:2222"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
      USER_NAME: fsuser
      USER_PASSWORD: fspass
      PASSWORD_ACCESS: "true"
      SUDO_ACCESS: "false"
      LOG_STDOUT: "true"
