// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
	"time"
)

func main() {
	// GetContext reads the object at path using the caller-provided context.

	// Example: read an object with a timeout
	disk, _ := storage.Build(localstorage.Config{
		Remote: "/tmp/storage-get-context",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	cs := disk.(storage.ContextStorage)
	data, _ := cs.GetContext(ctx, "docs/readme.txt")
	fmt.Println(string(data))
	// Output: hello
}
