// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command redisstorage_config_define_redis_storage_config is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/redisstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines a Redis-backed storage disk for distributed temporary blobs.

	// Example: define redis storage config
	cfg := redisstorage.Config{
		Addr: "127.0.0.1:6379",
	}
	_ = cfg

}
