// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/redisstorage"

func main() {
	// Config defines a Redis-backed storage disk for distributed temporary blobs.

	// Example: define redis storage config
	cfg := redisstorage.Config{
		Addr: "127.0.0.1:6379",
	}
	_ = cfg

}
