// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/ftpstorage"

func main() {
	// New constructs FTP-backed storage using jlaffaye/ftp.

	// Example: ftp storage
	fs, _ := ftpstorage.New(ftpstorage.Config{
		Host:     "127.0.0.1",
		User:     "demo",
		Password: "secret",
	})
	_ = fs
}
