// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command ftpstorage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/ftpstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs FTP-backed storage using jlaffaye/ftp.

	// Example: ftp storage
	fs, _ := ftpstorage.New(ftpstorage.Config{
		Host:     "127.0.0.1",
		User:     "demo",
		Password: "secret",
	})
	_ = fs
}
