// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Storage is the public interface for interacting with a storage backend.
	//
	// Semantics:
	//   - Put overwrites an existing object at the same path.
	//   - List is one-level and non-recursive.
	//   - List with an empty path lists from the disk root or prefix root.
	//   - Walk is recursive and may return ErrUnsupported on drivers that do not implement it.
	//   - URL returns a usable access URL when the driver supports it.
	//   - Unsupported operations should return ErrUnsupported.

	// Example: use the storage interface
	var disk storage.Storage
	disk, _ = storage.Build(localstorage.Config{
		Remote: "/tmp/storage-interface",
	})
	_ = disk
}
