// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage is generated so this documented storage example remains directly runnable.
package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Storage is the public interface for interacting with a storage backend.
	//
	// Semantics:
	//   - Put overwrites an existing object at the same path.
	//   - MakeDir creates a directory-like prefix and may be implemented as a
	//     backend-specific directory marker on object stores.
	//   - List is one-level, non-recursive, and sorted lexicographically by Path.
	//   - List with an empty path lists from the disk root or prefix root.
	//   - Walk is recursive and visits entries lexicographically by Path.
	//   - URL returns a usable access URL when the driver supports it.
	//   - Copy overwrites the destination object when the backend supports copy semantics.
	//   - Move relocates an object or directory tree and may be implemented as copy followed by delete.
	//     Directory moves roll back destination entries if copying fails. A failure while deleting
	//     the source may leave a complete destination alongside the undeleted source remainder.
	//   - Unsupported operations should return ErrUnsupported.

	// Example: use the storage interface
	var disk storage.Storage
	disk, _ = storage.Build(localstorage.Config{
		Root: "/tmp/storage-interface",
	})
	_ = disk
}
