// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command dropboxstorage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/dropboxstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs Dropbox-backed storage using the official SDK.

	// Example: dropbox storage
	fs, _ := dropboxstorage.New(dropboxstorage.Config{
		Token: "token",
	})
	_ = fs
}
