// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/dropboxstorage"

func main() {
	// New constructs Dropbox-backed storage using the official SDK.

	// Example: dropbox storage
	fs, _ := dropboxstorage.New(dropboxstorage.Config{
		Token: "token",
	})
	_ = fs
}
