// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/redisstorage"

func main() {
	// New constructs Redis-backed storage using go-redis.

	// Example: redis storage
	fs, _ := redisstorage.New(redisstorage.Config{
		Addr:   "127.0.0.1:6379",
		Prefix: "scratch",
	})
	_ = fs
}
