// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command redisstorage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/redisstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs Redis-backed storage using go-redis.

	// Example: redis storage
	fs, _ := redisstorage.New(redisstorage.Config{
		Addr:   "127.0.0.1:6379",
		Prefix: "scratch",
	})
	_ = fs
}
