// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command dropboxstorage_config_define_dropbox_storage_config is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/dropboxstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines a Dropbox-backed storage disk.

	// Example: define dropbox storage config
	cfg := dropboxstorage.Config{
		Token: "token",
	}
	_ = cfg

}
