// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_move_move_an_object is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Move moves the object or directory tree at src to dst.

	// Example: move an object
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-move",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))
	_ = disk.Move("docs/readme.txt", "docs/archive.txt")

	ok, _ := disk.Exists("docs/readme.txt")
	fmt.Println(ok)
	// Output: false

}
