// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/rclonestorage"

func main() {
	// Config defines an rclone-backed storage disk.

	// Example: define rclone storage config with all fields
	cfg := rclonestorage.Config{
		Remote:           "local:",
		Prefix:           "sandbox",                 // default: ""
		RcloneConfigPath: "/path/to/rclone.conf",    // default: ""
		RcloneConfigData: "[local]\ntype = local\n", // default: ""
	}
	_ = cfg
}
