// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command manager_disk is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Disk returns a named disk or an error if it does not exist.

	// Example: get a named disk
	mgr, _ := storage.New(storage.Config{
		Default: "local",
		Disks: map[storage.DiskName]storage.DriverConfig{
			"local":   localstorage.Config{Root: "/tmp/storage-default"},
			"uploads": localstorage.Config{Root: "/tmp/storage-uploads"},
		},
	})

	fs, _ := mgr.Disk("uploads")
	fmt.Println(fs != nil)
	// Output: true
}
