// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command sftpstorage_config_define_sftp_storage_config_with_all_fields is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/sftpstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an SFTP-backed storage disk.

	// Example: define sftp storage config with all fields
	cfg := sftpstorage.Config{
		Host:                  "127.0.0.1",
		Port:                  22,                  // default: 22
		User:                  "demo",              // default: "root"
		Password:              "secret",            // default: ""
		KeyPath:               "/path/id_ed25519",  // default: ""
		KnownHostsPath:        "/path/known_hosts", // default: ""
		InsecureIgnoreHostKey: false,               // default: false
		Prefix:                "uploads",           // default: ""
	}
	_ = cfg
}
