// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command sftpstorage_config_define_sftp_storage_config is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/sftpstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an SFTP-backed storage disk.

	// Example: define sftp storage config
	cfg := sftpstorage.Config{
		Host:     "127.0.0.1",
		User:     "demo",
		Password: "secret",
	}
	_ = cfg

}
