// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command rclonestorage_s3remote_define_an_s3_remote is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage/driver/rclonestorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// S3Remote defines parameters for constructing an rclone S3 remote.

	// Example: define an s3 remote
	remote := rclonestorage.S3Remote{
		Name:            "assets",
		Region:          "us-east-1",
		AccessKeyID:     "key",
		SecretAccessKey: "secret",
	}
	fmt.Println(remote.Name)
	// Output: assets

}
