// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command joinprefix is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// JoinPrefix combines a disk prefix with a path using slash separators.

	// Example: join a disk prefix and path
	fmt.Println(storage.JoinPrefix("assets", "logo.svg"))
	// Output: assets/logo.svg
}
