// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Config defines named disks using typed driver configs.

	// Example: define manager config
	cfg := storage.Config{
		Default: "local",
		Disks: map[storage.DiskName]storage.DriverConfig{
			"local": localstorage.Config{Remote: "/tmp/storage-manager"},
		},
	}
	_ = cfg
}
