// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command config is generated so this documented storage example remains directly runnable.
package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines named disks using typed driver configs.

	// Example: define manager config
	cfg := storage.Config{
		Default: "local",
		Disks: map[storage.DiskName]storage.DriverConfig{
			"local": localstorage.Config{Root: "/tmp/storage-manager"},
		},
	}
	_ = cfg
}
