// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// List returns the immediate children under path.

	// Example: list a directory
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-list",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	entries, _ := disk.List("docs")
	fmt.Println(entries[0].Path)
	// Output: docs/readme.txt
}
