// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command resolvedconfig is generated so this documented storage example remains directly runnable.
package main

import (
	"context"
	"fmt"
	"github.com/goforj/storage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// ResolvedConfig is the normalized internal config passed to registered drivers.
	// Users should prefer typed driver configs and treat this as registry adapter
	// glue, not the primary construction API.

	// Example: inspect a resolved config in a driver factory
	factory := storage.DriverFactory(func(ctx context.Context, cfg storage.ResolvedConfig) (storage.Storage, error) {
		fmt.Println(cfg.Driver)
		// Output: memory
		return nil, nil
	})

	_, _ = factory(context.Background(), storage.ResolvedConfig{Driver: "memory"})
}
