// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command manager_default is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Default returns the default disk or panics if misconfigured.

	// Example: get the default disk
	mgr, _ := storage.New(storage.Config{
		Default: "local",
		Disks: map[storage.DiskName]storage.DriverConfig{
			"local": localstorage.Config{Root: "/tmp/storage-default"},
		},
	})

	fs := mgr.Default()
	fmt.Println(fs != nil)
	// Output: true
}
