// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage/driver/rclonestorage"
)

func main() {
	// LocalRemote defines a local backend configuration.

	// Example: define a local remote with all fields
	remote := rclonestorage.LocalRemote{
		Name: "local",
	}
	fmt.Println(remote.Name)
	// Output: local
}
