// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command rclonestorage_localremote_define_a_local_remote_with_all_fields is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage/driver/rclonestorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// LocalRemote defines a local backend configuration.

	// Example: define a local remote with all fields
	remote := rclonestorage.LocalRemote{
		Name: "local",
	}
	fmt.Println(remote.Name)
	// Output: local
}
