// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command registerdriver is generated so this documented storage example remains directly runnable.
package main

import (
	"context"
	"github.com/goforj/storage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// RegisterDriver makes a driver available to the Manager. It panics on duplicate registrations.

	// Example: register a custom driver
	storage.RegisterDriver("memory", func(ctx context.Context, cfg storage.ResolvedConfig) (storage.Storage, error) {
		return nil, nil
	})
}
