// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command s3storage_config_define_s3_storage_config is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/s3storage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an S3-backed storage disk.

	// Example: define s3 storage config
	cfg := s3storage.Config{
		Bucket: "uploads",
		Region: "us-east-1",
	}
	_ = cfg

}
