// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/s3storage"

func main() {
	// Config defines an S3-backed storage disk.

	// Example: define s3 storage config
	cfg := s3storage.Config{
		Bucket: "uploads",
		Region: "us-east-1",
	}
	_ = cfg

}
