// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command rclonestorage_mustrenderlocal is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage/driver/rclonestorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// MustRenderLocal panics on error.

	// Example: render a local remote without handling the error
	cfg := rclonestorage.MustRenderLocal(rclonestorage.LocalRemote{Name: "local"})
	fmt.Println(cfg)
	// Output:
	// [local]
	// type = local
}
