// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command localstorage_config_define_local_storage_config_with_all_fields is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/localstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines local storage rooted at a filesystem path.

	// Example: define local storage config with all fields
	cfg := localstorage.Config{
		Root:   "/tmp/storage-local",
		Prefix: "sandbox", // default: ""
	}
	_ = cfg
}
