// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/localstorage"

func main() {
	// Config defines local storage rooted at a filesystem path.

	// Example: define local storage config with all fields
	cfg := localstorage.Config{
		Root:   "/tmp/storage-local",
		Prefix: "sandbox", // default: ""
	}
	_ = cfg
}
