// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command gcsstorage_config_define_gcs_storage_config is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/gcsstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines a GCS-backed storage disk.

	// Example: define gcs storage config
	cfg := gcsstorage.Config{
		Bucket: "uploads",
	}
	_ = cfg

}
