// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Get reads the object at path.

	// Example: read an object
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-get",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	data, _ := disk.Get("docs/readme.txt")
	fmt.Println(string(data))
	// Output: hello
}
