// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command entry is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Entry represents an item returned by List.
	//
	// Path is relative to the storage namespace, not an OS-native path.
	// Directory-like entries are listing artifacts, not a promise of POSIX-style
	// storage semantics.

	// Example: inspect a listed entry
	entry := storage.Entry{
		Path:  "docs/readme.txt",
		Size:  5,
		IsDir: false,
	}
	fmt.Println(entry.Path, entry.IsDir)
	// Output: docs/readme.txt false
}
