// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Copy copies the object at src to dst.

	// Example: copy an object
	disk, _ := storage.Build(localstorage.Config{
		Remote: "/tmp/storage-copy",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))
	_ = disk.Copy("docs/readme.txt", "docs/copy.txt")

	data, _ := disk.Get("docs/copy.txt")
	fmt.Println(string(data))
	// Output: hello
}
