// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/rclonestorage"

func main() {
	// New constructs an rclone-backed storage. All disks share a single config path.

	// Example: rclone storage with inline config
	fs, _ := rclonestorage.New(rclonestorage.Config{
		Remote: "localdisk:/tmp/storage",
		RcloneConfigData: `

	[localdisk]
	type = local
	`,
	})
	_ = fs
}
