// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command s3storage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/s3storage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs S3-backed storage using AWS SDK v2.

	// Example: s3 storage
	fs, _ := s3storage.New(s3storage.Config{
		Bucket: "uploads",
		Region: "us-east-1",
	})
	_ = fs
}
