// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"context"
	"github.com/goforj/storage/driver/s3storage"
)

func main() {
	// New constructs S3-backed storage using AWS SDK v2.

	// Example: s3 storage
	fs, _ := s3storage.New(context.Background(), s3storage.Config{
		Bucket: "uploads",
		Region: "us-east-1",
	})
	_ = fs
}
