// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command rclonestorage_renderlocal is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage/driver/rclonestorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// RenderLocal returns ini-formatted rclone config for a local backend.

	// Example: render a local remote
	cfg, _ := rclonestorage.RenderLocal(rclonestorage.LocalRemote{Name: "local"})
	fmt.Println(cfg)
	// Output:
	// [local]
	// type = local
}
