// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command ftpstorage_config_define_ftp_storage_config_with_all_fields is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/ftpstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an FTP-backed storage disk.

	// Example: define ftp storage config with all fields
	cfg := ftpstorage.Config{
		Host:               "127.0.0.1",
		Port:               21,        // default: 21
		User:               "demo",    // default: ""
		Password:           "secret",  // default: ""
		TLS:                false,     // default: false
		InsecureSkipVerify: false,     // default: false
		Prefix:             "uploads", // default: ""
	}
	_ = cfg
}
