// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/s3storage"
)

func main() {
	// URL returns a usable access URL when the driver supports it.

	// Example: request an object url
	disk, _ := storage.Build(s3storage.Config{
		Bucket: "uploads",
		Region: "us-east-1",
	})

	url, _ := disk.URL("docs/readme.txt")
	_ = url // signed object URL

}
