// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_url_request_an_object_url is generated so this documented storage example remains directly runnable.
package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/s3storage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// URL returns a usable access URL when the driver supports it.

	// Example: request an object url
	disk, _ := storage.Build(s3storage.Config{
		Bucket: "uploads",
		Region: "us-east-1",
	})

	url, _ := disk.URL("docs/readme.txt")
	_ = url

}
