// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_makedir is generated so this documented storage example remains directly runnable.
package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// MakeDir creates a directory-like entry at path.

	// Example: create a directory
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-mkdir",
	})
	_ = disk.MakeDir("docs/archive")
}
