// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// MakeDir creates a directory-like entry at path.

	// Example: create a directory
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-mkdir",
	})
	_ = disk.MakeDir("docs/archive")
}
