// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command memorystorage_config_define_memory_storage_config_with_all_fields is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/memorystorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an in-memory storage disk.

	// Example: define memory storage config with all fields
	cfg := memorystorage.Config{
		Prefix: "sandbox", // default: ""
	}
	_ = cfg
}
