// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command rclonestorage_s3remote_define_an_s3_remote_with_all_fields is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage/driver/rclonestorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// S3Remote defines parameters for constructing an rclone S3 remote.

	// Example: define an s3 remote with all fields
	remote := rclonestorage.S3Remote{
		Name:               "assets",
		Endpoint:           "http://localhost:9000", // default: ""
		Region:             "us-east-1",
		AccessKeyID:        "key",
		SecretAccessKey:    "secret",
		Provider:           "AWS",     // default: "AWS"
		PathStyle:          false,     // default: false
		BucketACL:          "private", // default: ""
		UseUnsignedPayload: false,     // default: false
	}
	fmt.Println(remote.Name)
	// Output: assets
}
