// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command localstorage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/localstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs local storage rooted at cfg.Root with an optional prefix.

	// Example: local storage
	fs, _ := localstorage.New(localstorage.Config{
		Root:   "/tmp/storage-local",
		Prefix: "sandbox",
	})
	_ = fs
}
