// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/localstorage"

func main() {
	// New constructs local storage rooted at cfg.Root with an optional prefix.

	// Example: local storage
	fs, _ := localstorage.New(localstorage.Config{
		Root:   "/tmp/storage-local",
		Prefix: "sandbox",
	})
	_ = fs
}
