// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command ftpstorage_config_define_ftp_storage_config is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/ftpstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an FTP-backed storage disk.

	// Example: define ftp storage config
	cfg := ftpstorage.Config{
		Host:     "127.0.0.1",
		User:     "demo",
		Password: "secret",
	}
	_ = cfg

}
