// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/memorystorage"

func main() {
	// Config defines an in-memory storage disk.

	// Example: define memory storage config
	cfg := memorystorage.Config{}
	_ = cfg

}
