// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// CountFiles returns the recursive count of non-directory entries under path.
	//
	// CountFiles uses Walk under the hood, so it works across drivers that support
	// recursive traversal.

	// Example: count files on a disk
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-count-files",
	})
	_ = disk.MakeDir("docs/archive")
	_ = disk.Put("docs/readme.txt", []byte("hello"))
	_ = disk.Put("docs/archive/guide.txt", []byte("guide"))

	total, _ := storage.CountFiles(disk, "docs")
	fmt.Println(total)
	// Output: 2
}
