// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command driverfactory is generated so this documented storage example remains directly runnable.
package main

import (
	"context"
	"github.com/goforj/storage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// DriverFactory constructs a Storage for a given normalized disk configuration.

	// Example: declare a driver factory
	factory := storage.DriverFactory(func(ctx context.Context, cfg storage.ResolvedConfig) (storage.Storage, error) {
		return nil, nil
	})
	_ = factory
}
