// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_walk is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Walk visits entries recursively in deterministic path order.

	// Example: walk a local directory
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-walk",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	err := disk.Walk("", func(entry storage.Entry) error {
		fmt.Println(entry.Path)
		return nil
	})
	fmt.Println(err == nil)
	// Output:
	// docs
	// docs/readme.txt
	// true
}
