// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"errors"
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Walk visits entries recursively when the backend supports it.

	// Example: walk a backend when supported
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-walk",
	})

	err := disk.Walk("", func(entry storage.Entry) error {
		fmt.Println(entry.Path)
		return nil
	})
	fmt.Println(errors.Is(err, storage.ErrUnsupported))
	// Output: true
}
