// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command gcsstorage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/gcsstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs GCS-backed storage using cloud.google.com/go/storage.

	// Example: gcs storage
	fs, _ := gcsstorage.New(gcsstorage.Config{
		Bucket: "uploads",
	})
	_ = fs
}
