// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/gcsstorage"

func main() {
	// New constructs GCS-backed storage using cloud.google.com/go/storage.

	// Example: gcs storage
	fs, _ := gcsstorage.New(gcsstorage.Config{
		Bucket: "uploads",
	})
	_ = fs
}
