// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command rclonestorage_config_define_rclone_storage_config is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/rclonestorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an rclone-backed storage disk.

	// Example: define rclone storage config
	cfg := rclonestorage.Config{
		Remote: "local:",
		Prefix: "sandbox",
	}
	_ = cfg

}
