// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_put is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Put writes an object at path, overwriting any existing object.

	// Example: write an object
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-put",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))
	fmt.Println("stored")
	// Output: stored
}
