// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command s3storage_config_define_s3_storage_config_with_all_fields is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/s3storage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Config defines an S3-backed storage disk.

	// Example: define s3 storage config with all fields
	cfg := s3storage.Config{
		Bucket:          "uploads",
		Endpoint:        "http://localhost:9000", // default: ""
		Region:          "us-east-1",
		AccessKeyID:     "minioadmin", // default: ""
		SecretAccessKey: "minioadmin", // default: ""
		UsePathStyle:    true,         // default: false
		UnsignedPayload: false,        // default: false
		Prefix:          "assets",     // default: ""
	}
	_ = cfg
}
