// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Exists reports whether an object exists at path.

	// Example: check for an object
	disk, _ := storage.Build(localstorage.Config{
		Remote: "/tmp/storage-exists",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	ok, _ := disk.Exists("docs/readme.txt")
	fmt.Println(ok)
	// Output: true
}
