// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_exists is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Exists reports whether an object exists at path.

	// Example: check for an object
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-exists",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	ok, _ := disk.Exists("docs/readme.txt")
	fmt.Println(ok)
	// Output: true
}
