// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command storage_stat is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// Stat returns the entry at path.

	// Example: stat an object
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-stat",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	entry, _ := disk.Stat("docs/readme.txt")
	fmt.Println(entry.Path, entry.Size)
	// Output: docs/readme.txt 5
}
