// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Stat returns the entry at path.

	// Example: stat an object
	disk, _ := storage.Build(localstorage.Config{
		Remote: "/tmp/storage-stat",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))

	entry, _ := disk.Stat("docs/readme.txt")
	fmt.Println(entry.Path, entry.Size)
	// Output: docs/readme.txt 5
}
