// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command new is generated so this documented storage example remains directly runnable.
package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs a Manager and eagerly initializes all disks.

	// Example: build a manager with named disks
	mgr, _ := storage.New(storage.Config{
		Default: "local",
		Disks: map[storage.DiskName]storage.DriverConfig{
			"local":  localstorage.Config{Root: "/tmp/storage-local"},
			"assets": localstorage.Config{Root: "/tmp/storage-assets", Prefix: "public"},
		},
	})
	_ = mgr
}
