// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import "github.com/goforj/storage/driver/memorystorage"

func main() {
	// New constructs in-memory storage.

	// Example: memory storage
	fs, _ := memorystorage.New(memorystorage.Config{
		Prefix: "sandbox",
	})
	_ = fs
}
