// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command memorystorage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/memorystorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs in-memory storage.

	// Example: memory storage
	fs, _ := memorystorage.New(memorystorage.Config{
		Prefix: "sandbox",
	})
	_ = fs
}
