// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command diskname is generated so this documented storage example remains directly runnable.
package main

import (
	"fmt"
	"github.com/goforj/storage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// DiskName is a typed identifier for configured disks.

	// Example: declare a disk name
	const uploads storage.DiskName = "uploads"
	fmt.Println(uploads)
	// Output: uploads
}
