// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Delete removes the object at path.

	// Example: delete an object
	disk, _ := storage.Build(localstorage.Config{
		Remote: "/tmp/storage-delete",
	})
	_ = disk.Put("docs/readme.txt", []byte("hello"))
	_ = disk.Delete("docs/readme.txt")

	ok, _ := disk.Exists("docs/readme.txt")
	fmt.Println(ok)
	// Output: false
}
