// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command sftpstorage_new is generated so this documented storage example remains directly runnable.
package main

import "github.com/goforj/storage/driver/sftpstorage"

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// New constructs SFTP-backed storage using ssh and pkg/sftp.

	// Example: sftp storage
	fs, _ := sftpstorage.New(sftpstorage.Config{
		Host:     "127.0.0.1",
		User:     "demo",
		Password: "secret",
	})
	_ = fs
}
