// Code generated by docs/examplegen/main.go. DO NOT EDIT.

package main

import (
	"fmt"
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

func main() {
	// Move moves the object or directory tree at src to dst.

	// Example: move a directory tree
	disk, _ := storage.Build(localstorage.Config{
		Root: "/tmp/storage-move-dir",
	})
	_ = disk.MakeDir("docs/archive")
	_ = disk.Put("docs/archive/readme.txt", []byte("hello"))
	_ = disk.Move("docs/archive", "docs/published")

	entry, _ := disk.Stat("docs/published")
	fmt.Println(entry.IsDir)
	// Output: true
}
