// Code generated by docs/examplegen/main.go. DO NOT EDIT.

// Command driverconfig is generated so this documented storage example remains directly runnable.
package main

import (
	"github.com/goforj/storage"
	"github.com/goforj/storage/driver/localstorage"
)

// main keeps this generated storage example executable so documentation drift fails during compilation.
func main() {
	// DriverConfig is implemented by typed driver configs such as local.Config or
	// s3storage.Config. It is the public config boundary for Manager and Build.

	// Example: pass a typed driver config
	var cfg storage.DriverConfig = localstorage.Config{
		Root: "/tmp/storage-config",
	}
	_ = cfg
}
